package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("build")) {
    check(name == "build") {
        "Unexpected name: '$name'"
    }
    name = "Build"

    check(artifactRules == "") {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = "packages/my-react-app/build => my-react-app.zip"

    expectSteps {
    }
    steps {
        insert(0) {
            script {
                scriptContent = """
                    lerna bootstrap
                    lerna run build
                """.trimIndent()
            }
        }
    }
}
